# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'macOS-latest'

steps:
- task: MSBuild@1
  displayName: Build
  inputs:
    solution: 'repro-dotnet-5-mac.csproj'

